# Generated by Django 3.0.5 on 2020-05-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='phone_num',
        ),
    ]
