# Generated by Django 3.0.5 on 2020-05-03 03:02

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kid'), ('S', 'Sun'), ('O', 'Other')], max_length=1)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('inventory', models.IntegerField(blank=True, default=0)),
                ('image', models.ImageField(blank=True, default=0, null=True, upload_to='')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'On Sale'), ('N', 'New')], max_length=1)),
                ('off_percentage', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
