# Generated by Django 3.0.5 on 2020-05-17 00:30

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BaseCurve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=22)),
                ('sample', models.ImageField(blank=True, null=True, upload_to=product.models.color_sample_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='ColorsGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=product.models.get_color_gallery_slug, unique=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Color')),
            ],
        ),
        migrations.CreateModel(
            name='ContactColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cyl', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Diameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HighLow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hl', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('C', 'Contact'), ('S', 'Sun'), ('O', 'Other')], default='O', max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kid'), ('U', 'Unisex'), ('O', 'Other')], default='U', max_length=1)),
                ('description', models.TextField(blank=True, default='')),
                ('size', models.CharField(choices=[('SM', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('NA', 'NA')], default='NA', max_length=2)),
                ('shape', models.CharField(choices=[('RT', 'Rectangle'), ('RD', 'Round'), ('A', 'Aviator'), ('G', 'Geometric'), ('NA', 'NA')], default='NA', max_length=2)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('inventory', models.IntegerField(blank=True, default=0)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'On Sale'), ('N', 'New')], default='P', max_length=1)),
                ('off_percentage', models.FloatField(blank=True, default=0, null=True)),
                ('add_on_power', models.ManyToManyField(blank=True, null=True, to='product.AddOnPower')),
                ('axis', models.ManyToManyField(blank=True, null=True, to='product.Axis')),
                ('base_curve', models.ManyToManyField(blank=True, default=None, null=True, to='product.BaseCurve')),
                ('contact_color', models.ManyToManyField(blank=True, null=True, to='product.ContactColor')),
                ('cylinder', models.ManyToManyField(blank=True, null=True, to='product.Cylinder')),
                ('diameter', models.ManyToManyField(blank=True, null=True, to='product.Diameter')),
                ('dn', models.ManyToManyField(blank=True, null=True, to='product.DN')),
                ('high_low', models.ManyToManyField(blank=True, null=True, to='product.HighLow')),
                ('power', models.ManyToManyField(blank=True, null=True, to='product.Power')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product.models.gallery_images_directory_path, verbose_name='Image')),
                ('color_gallery', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.ColorsGallery')),
            ],
        ),
        migrations.AddField(
            model_name='colorsgallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors_gallery', to='product.Product'),
        ),
    ]
