# Generated by Django 3.0.5 on 2020-05-08 03:53

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=22)),
                ('sample', models.ImageField(blank=True, null=True, upload_to=product.models.color_sample_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='ColorsGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kid'), ('S', 'Sun'), ('O', 'Other')], max_length=1)),
                ('description', models.TextField(blank=True, default='')),
                ('size', models.CharField(choices=[('SM', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('NA', 'NA')], default='NA', max_length=2)),
                ('shape', models.CharField(choices=[('RT', 'Rectangle'), ('RD', 'Round'), ('A', 'Aviator'), ('G', 'Geometric'), ('NA', 'NA')], default='NA', max_length=2)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('inventory', models.IntegerField(blank=True, default=0)),
                ('image', models.ImageField(blank=True, default=0, null=True, upload_to=product.models.image_directory_path)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'On Sale'), ('N', 'New')], max_length=1)),
                ('off_percentage', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product.models.gallery_images_directory_path, verbose_name='Image')),
                ('color_gallery', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.ColorsGallery')),
            ],
        ),
        migrations.AddField(
            model_name='colorsgallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors_gallery', to='product.Product'),
        ),
    ]
