# Generated by Django 3.0.5 on 2020-05-08 06:45

import autoslug.fields
from django.db import migrations
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorsgallery',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='aaa', editable=False, populate_from=product.models.get_color_gallery_slug, unique=True),
            preserve_default=False,
        ),
    ]
