# Generated by Django 3.0.5 on 2020-04-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200429_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
