# Generated by Django 3.0.5 on 2020-05-11 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_colorsgallery_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
