# Generated by Django 3.0.5 on 2020-07-15 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200516_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='add_on_power',
        ),
        migrations.RemoveField(
            model_name='product',
            name='axis',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_curve',
        ),
        migrations.RemoveField(
            model_name='product',
            name='contact_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cylinder',
        ),
        migrations.RemoveField(
            model_name='product',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dn',
        ),
        migrations.RemoveField(
            model_name='product',
            name='high_low',
        ),
        migrations.RemoveField(
            model_name='product',
            name='power',
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Product')),
                ('add_on_power', models.ManyToManyField(blank=True, null=True, to='product.AddOnPower')),
                ('axis', models.ManyToManyField(blank=True, null=True, to='product.Axis')),
                ('base_curve', models.ManyToManyField(blank=True, default=None, null=True, to='product.BaseCurve')),
                ('contact_color', models.ManyToManyField(blank=True, null=True, to='product.ContactColor')),
                ('cylinder', models.ManyToManyField(blank=True, null=True, to='product.Cylinder')),
                ('diameter', models.ManyToManyField(blank=True, null=True, to='product.Diameter')),
                ('dn', models.ManyToManyField(blank=True, null=True, to='product.DN')),
                ('high_low', models.ManyToManyField(blank=True, null=True, to='product.HighLow')),
                ('power', models.ManyToManyField(blank=True, null=True, to='product.Power')),
            ],
            bases=('product.product',),
        ),
    ]
