# Generated by Django 3.0.5 on 2020-04-16 16:06

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=0, editable=False, populate_from='product', unique_with=('product',)),
            preserve_default=False,
        ),
    ]
