# Generated by Django 3.0.5 on 2020-04-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_auto_20200416_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ref_code',
            field=models.CharField(default=0, max_length=22),
            preserve_default=False,
        ),
    ]
