# Generated by Django 3.0.5 on 2020-04-17 16:45

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_auto_20200416_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=0, editable=False, populate_from='ref_code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
