# Generated by Django 3.0.5 on 2020-04-12 21:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0002_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='productId',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
    ]
