# Generated by Django 3.0.5 on 2020-04-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0003_auto_20200412_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='cart', to='optical.Product'),
        ),
    ]
