# Generated by Django 3.0.5 on 2020-04-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0005_auto_20200409_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
