# Generated by Django 3.0.5 on 2020-04-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0006_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserOF',
        ),
    ]
