# Generated by Django 3.0.5 on 2020-04-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='final_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
