# Generated by Django 3.0.5 on 2020-05-05 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_address_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
