# Generated by Django 3.0.5 on 2020-05-05 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_remove_payment_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='default',
        ),
    ]
