# Generated by Django 3.0.5 on 2020-05-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_coupon_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_saved',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
