# Generated by Django 3.0.5 on 2020-05-05 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_auto_20200505_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ref_code',
        ),
    ]
