# Generated by Django 3.0.5 on 2020-05-06 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0017_remove_cart_ref_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='being_delivered',
            new_name='is_delivered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='received',
            new_name='is_received',
        ),
    ]
